const productSchema={type:'object',additionalProperties:false,required:['category','name','specification','store','price','quantity','url','availability','is_new'],properties:{category:{type:'string'},name:{type:'string'},specification:{type:'string'},store:{type:'string'},price:{type:'number'},quantity:{type:'integer'},url:{type:'string'},availability:{type:'string'},is_new:{type:'boolean'}}};
const tierSchema={type:'object',additionalProperties:false,required:['level','name','description','design_notes','palette','image_prompt','products','total'],properties:{level:{type:'string',enum:['Económica','Intermedia','Premium']},name:{type:'string'},description:{type:'string'},design_notes:{type:'string'},palette:{type:'array',items:{type:'string'}},image_prompt:{type:'string'},total:{type:'number'},products:{type:'array',minItems:1,items:productSchema}}};
export default async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Método no permitido'});
 if(!process.env.OPENAI_API_KEY)return res.status(500).json({error:'Falta configurar OpenAI'});
 try{
  const {tier,modification,brief,iteration}=req.body||{};
  if(!tier||!modification?.trim())return res.status(400).json({error:'Falta la propuesta o la modificación'});
  if(Number(iteration)>10)return res.status(400).json({error:'Se alcanzó el máximo de 10 iteraciones para esta propuesta'});
  const prompt=`Eres arquitecto de interiores y comprador experto en Chile. Debes REFINAR una propuesta existente sin rediseñarla completa. Esta es la propuesta actual: ${JSON.stringify(tier)}. Brief original: ${JSON.stringify(brief||{})}. Cambio solicitado por el usuario: ${JSON.stringify(modification)}. REGLA CRÍTICA: conserva absolutamente todo lo que el usuario NO pidió modificar. Cambia solo lo necesario para cumplir la solicitud. Actualiza descripción, notas, paleta e image_prompt solo en lo afectado. En products conserva idénticos los productos no afectados. Para cualquier producto agregado o reemplazado por esta modificación, busca nuevamente en la web un producto REAL y comprable en Santiago de Chile, priorizando Mercado Libre Chile, Falabella, Paris, Ripley, Sodimac, Easy, IKEA Chile, Casaideas y tiendas chilenas pertinentes. La URL debe ser directa al producto. Nunca inventes enlaces, stock ni precio. Marca is_new=true SOLO en productos nuevos o reemplazados en esta iteración; todos los demás is_new=false. El total debe ser la suma actualizada de price*quantity. image_prompt debe describir la edición incremental sobre la imagen actual y repetir explícitamente: mantener sin cambios todos los elementos no mencionados por el usuario. Responde solo en español.`;
  const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:'gpt-5.6',reasoning:{effort:'medium'},tools:[{type:'web_search',user_location:{type:'approximate',country:'CL',city:'Santiago',region:'Metropolitana'}}],include:['web_search_call.action.sources'],input:prompt,text:{format:{type:'json_schema',name:'fotodecora_refine',strict:true,schema:tierSchema}}})});
  const d=await r.json();if(!r.ok)throw new Error(d.error?.message||'No se pudo actualizar la propuesta');
  const txt=d.output?.flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text||d.output_text;
  const updated=JSON.parse(txt);return res.json(updated);
 }catch(e){return res.status(500).json({error:e.message||'No se pudo refinar la propuesta'})}
}
